(function(g){var window=this;'use strict';var qub=function(a,b){g.V.call(this,{I:"button",Ka:["ytp-miniplayer-expand-watch-page-button","ytp-button","ytp-miniplayer-button-top-left"],X:{title:"{{title}}","data-tooltip-target-id":"ytp-miniplayer-expand-watch-page-button","aria-keyshortcuts":"i","data-title-no-tooltip":"{{data-title-no-tooltip}}"},V:[{I:"svg",X:{height:"24px",version:"1.1",viewBox:"0 0 24 24",width:"24px"},V:[{I:"g",X:{fill:"none","fill-rule":"evenodd",stroke:"none","stroke-width":"1"},V:[{I:"g",X:{transform:"translate(12.000000, 12.000000) scale(-1, 1) translate(-12.000000, -12.000000) "},
V:[{I:"path",X:{d:"M19,19 L5,19 L5,5 L12,5 L12,3 L5,3 C3.89,3 3,3.9 3,5 L3,19 C3,20.1 3.89,21 5,21 L19,21 C20.1,21 21,20.1 21,19 L21,12 L19,12 L19,19 Z M14,3 L14,5 L17.59,5 L7.76,14.83 L9.17,16.24 L19,6.41 L19,10 L21,10 L21,3 L14,3 Z",fill:"#fff","fill-rule":"nonzero"}}]}]}]}]});this.J=a;this.listen("click",this.onClick,this);this.updateValue("title",g.$T(a,"Expand","i"));this.update({"data-title-no-tooltip":"Expand"});this.addOnDisposeCallback(g.XT(b.Oe(),this.element))},rub=function(a){g.V.call(this,
{I:"div",
S:"ytp-miniplayer-ui"});this.G=!1;this.player=a;this.T(a,"minimized",this.hh);this.T(a,"onStateChange",this.g3)},sub=function(a){g.NV.call(this,a);
this.B=new g.xK(this);this.j=new rub(this.player);this.j.hide();g.hU(this.player,this.j.element,4);a.isMinimized()&&(this.load(),g.mv(a.getRootNode(),"ytp-player-minimized",!0))};
g.x(qub,g.V);qub.prototype.onClick=function(){this.J.ib("onExpandMiniplayer")};g.x(rub,g.V);g.k=rub.prototype;
g.k.show=function(){this.j=new g.Su(this.e3,null,this);this.j.start();if(!this.G){this.tooltip=new g.ZX(this.player,this);g.O(this,this.tooltip);g.hU(this.player,this.tooltip.element,4);this.tooltip.scale=.6;this.ge=new g.rW(this.player);g.O(this,this.ge);this.B=new g.V({I:"div",S:"ytp-miniplayer-scrim"});g.O(this,this.B);this.B.Ia(this.element);this.T(this.B.element,"click",this.pT);var a=new g.V({I:"button",Ka:["ytp-miniplayer-close-button","ytp-button"],X:{"aria-label":"Close"},V:[g.MF()]});g.O(this,
a);a.Ia(this.B.element);this.T(a.element,"click",this.oT);a=new qub(this.player,this);g.O(this,a);a.Ia(this.B.element);this.C=new g.V({I:"div",S:"ytp-miniplayer-controls"});g.O(this,this.C);this.C.Ia(this.B.element);this.T(this.C.element,"click",this.pT);var b=new g.V({I:"div",S:"ytp-miniplayer-button-container"});g.O(this,b);b.Ia(this.C.element);a=new g.V({I:"div",S:"ytp-miniplayer-play-button-container"});g.O(this,a);a.Ia(this.C.element);var c=new g.V({I:"div",S:"ytp-miniplayer-button-container"});
g.O(this,c);c.Ia(this.C.element);this.N=new g.lX(this.player,this,!1);g.O(this,this.N);this.N.Ia(b.element);b=new g.kX(this.player,this);g.O(this,b);b.Ia(a.element);this.nextButton=new g.lX(this.player,this,!0);g.O(this,this.nextButton);this.nextButton.Ia(c.element);this.K=new g.SX(this.player,this);g.O(this,this.K);this.K.Ia(this.B.element);this.progressBar=new g.qX(this.player,this);g.O(this,this.progressBar);g.hU(this.player,this.progressBar.element,4);this.D=new g.V({I:"div",S:"ytp-miniplayer-buttons"});
g.O(this,this.D);g.hU(this.player,this.D.element,4);a=new g.V({I:"button",Ka:["ytp-miniplayer-close-button","ytp-button"],X:{"aria-label":"Close"},V:[g.MF()]});g.O(this,a);a.Ia(this.D.element);this.T(a.element,"click",this.oT);a=new g.V({I:"button",Ka:["ytp-miniplayer-replay-button","ytp-button"],X:{"aria-label":"Close"},V:[g.mxa()]});g.O(this,a);a.Ia(this.D.element);this.T(a.element,"click",this.iaa);this.T(this.player,"presentingplayerstatechange",this.f3);this.T(this.player,"appresize",this.Vb);
this.T(this.player,"fullscreentoggled",this.Vb);this.Vb();this.G=!0}0!==this.player.getPlayerState()&&g.V.prototype.show.call(this);this.progressBar.show();this.player.unloadModule("annotations_module")};
g.k.hide=function(){this.j&&(this.j.dispose(),this.j=void 0);g.V.prototype.hide.call(this);this.player.isMinimized()||(this.G&&this.progressBar.hide(),this.player.loadModule("annotations_module"))};
g.k.va=function(){this.j&&(this.j.dispose(),this.j=void 0);g.V.prototype.va.call(this)};
g.k.oT=function(){this.player.stopVideo();this.player.ib("onCloseMiniplayer")};
g.k.iaa=function(){this.player.playVideo()};
g.k.pT=function(a){if(a.target===this.B.element||a.target===this.C.element)g.rL(this.player.Tb())?this.player.pauseVideo():this.player.playVideo()};
g.k.hh=function(){g.mv(this.player.getRootNode(),"ytp-player-minimized",this.player.isMinimized())};
g.k.Zf=function(){this.progressBar.Qc();this.K.Qc()};
g.k.e3=function(){this.Zf();this.j&&this.j.start()};
g.k.f3=function(a){g.uG(a.state,32)&&this.tooltip.hide()};
g.k.Vb=function(){g.C1a(this.progressBar,0,this.player.kb().getPlayerSize().width,!1);g.rX(this.progressBar)};
g.k.g3=function(a){this.player.isMinimized()&&(0===a?this.hide():this.show())};
g.k.Oe=function(){return this.tooltip};
g.k.Ot=function(a,b,c,d,e){var f=0,h=d=0,l=g.As(a);if(b){c=g.av(b,"ytp-prev-button")||g.av(b,"ytp-next-button");var m=g.av(b,"ytp-play-button"),n=g.av(b,"ytp-miniplayer-expand-watch-page-button");c?f=h=12:m?(b=g.ys(b,this.element),h=b.x,f=b.y-12):n&&(h=g.av(b,"ytp-miniplayer-button-top-left"),f=g.ys(b,this.element),b=g.As(b),h?(h=8,f=f.y+40):(h=f.x-l.width+b.width,f=f.y-20))}else h=c-l.width/2,d=25+(e||0);b=this.player.kb().getPlayerSize().width;e=f+(e||0);l=g.He(h,0,b-l.width);e?(a.style.top=e+"px",
a.style.bottom=""):(a.style.top="",a.style.bottom=d+"px");a.style.left=l+"px"};g.x(sub,g.NV);g.k=sub.prototype;g.k.onVideoDataChange=function(){if(this.player.getVideoData()){var a=this.player.getVideoAspectRatio(),b=16/9;a=a>b+.1||a<b-.1;g.mv(this.player.getRootNode(),"ytp-rounded-miniplayer-not-regular-wide-video",a)}};
g.k.create=function(){g.NV.prototype.create.call(this);this.B.T(this.player,"videodatachange",this.onVideoDataChange);this.onVideoDataChange()};
g.k.vl=function(){return!1};
g.k.load=function(){this.player.hideControls();this.j.show()};
g.k.unload=function(){this.player.showControls();this.j.hide()};g.MV("miniplayer",sub);})(_yt_player);
